type User {
  uID: String
  uName: String
}

type Auth {
    "When set, two factor authentication is activated"
    nonce: String
    "Includes the current uID and uName in payload"
    authToken: String
    error: String
}

type Query {
    me: User
}

type Mutation {
  "Login a user. Request for an authToken and refreshToken in response"
  login(
    username: String!
    password: String!
  ): Auth

  "if you use https://www.concrete5.org/marketplace/addons/two-factor-login-security you can check the nonce with this function"
  checkNonce(
      username: String!
      "Comming from the login function"
      nonce: String!
      "Inserted by the client from the google app"
      u2SAPass: String!
  ): Auth

  "Logout an user."
  logout: Auth

  forgotPassword(
      username: String!
      changePasswordUrl: String!
  ): [String]

  changePassword(
      password: String!
      passwordConfirm: String!
      token: String!
  ): [String]
}
