type User {
    uName: String!,
    uEmail: String!,
}

type UserResult {
    result: User,
    validationErrors: [String]!
}

enum Task {
  ADD,
  REMOVE
}

input Groups {
  name: String!
  task: Task!
}

type Mutation {
  "Returns result (userName and email), a validationErrors array"
  createUser(
      email: String!
      password: String!
      username: String
      reCaptchaToken: String!
      validationUrl: String
      userLocale: String
      "group by path with leading slash"
      groups: [Groups]
  ): UserResult!

  "Returns result (userName and email), a validationErrors array"
  updateUser(
      username: String!
      email: String
      validationUrl: String
      userLocale: String
      displayName: String
      "group by path with leading slash"
      groups: [Groups]
  ): UserResult!

"sends a validation email to the emailaddress of the user"
  sendValidationEmail(
      uName: String!,
      reCaptchaToken: String!
      validationUrl: String
      template: String
  ): Boolean!

  "validates the users emailaddress trough the token in the validation email"
  validateEmail(
      token: String!
      reCaptchaToken: String!
  ): Boolean!
  
}

type Query {
  getDisplayName(
    username: String!
  ): String!
}
