type User {
    userName: String!,
    email: String!,
}

type CreateUserResult {
    result: User,
    errors: [String]!
}

type Mutation {
  "Returns results (userName and email) and an error array"
  createUser(
      email: String!
      password: String!
      username: String
  ): CreateUserResult!
}

type Query {
  "gql file without query is not working :("
  dummy: String
}
